### ISSUE TITLE
Preprocessor directives in "stm32l1xx_ll_spi.h"

### ISSUE THREAD

**Issue by StressTest** [STMicroelectronics/STM32CubeL1#13] opened 2021-12-16 14:05 UTC
![image](https://user-images.githubusercontent.com/23332012/146387324-d1dead9d-9f6e-4dee-b322-ec4ef59148f8.png)

The code does not compile in Motorola mode.
Or is it a bug in CMSIS? 
Because file stm32l100xb.h has no information about Bit4 FRF from SPI_CR2.
(Missing lines
_#define SPI_CR2_FRF_Pos                 (4U)                               
#define SPI_CR2_FRF_Msk                 (0x1UL << SPI_CR2_FRF_Pos)      /*!< 0x00000010 */
#define SPI_CR2_FRF                     SPI_CR2_FRF_Msk                 /*!< Frame format */_
)
Description: https://community.st.com/s/question/0D53W00001FopFbSAJ/errors-in-the-configurator-of-the-stm32cubeide-for-microcontroller-stm32l100rb-not-observed-for-stm32f103-etc-low-layer-only

**Comment by ASELSTM** [comment] 2022-01-07 11:46
Hi @StressTest,

As mentioned in the reference manual [RM0038](https://www.st.com/resource/en/reference_manual/rm0038-stm32l100xx-stm32l151xx-stm32l152xx-and-stm32l162xx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf),  the `SPI_CR2_FRF` bit represents the SPI TI mode which is only available in the category 3, category 4, category 5 and category 6 devices. 

![image](https://user-images.githubusercontent.com/47858836/148536795-0b1fed11-cef0-47ec-a12c-1ba47f4335a9.png)

The  devices categories are described in the **"section 1.5 Product category definition"** of the reference manual. The STM32L100RB is a category 1 device as mentioned in the table below .

![image](https://user-images.githubusercontent.com/47858836/148536669-1f15bcd0-3b2e-4f5b-9dea-08a61199d3bf.png)

Therefore, the SPI TI mode, and consequently the `SPI_CR2_FRF` bit, is not available in the STM32L100RB part number. Thus, there is no bug in the CMSIS file, the issue is rather related to the CubeMX generation problem as the code generated by CubeMx, is calling the `LL_SPI_SetStandard` function which is managed by the `SPI_CR2_FRF` bit.

Unfortunately, we don't treat aspect related to CubeMX tool in our GitHub repositories.  They are rather treated at the [STM32CubeMX](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx) dedicated page of the **ST Community** . 

Please allow me then to close this thread. Thank you for your comprehension.

**Closed as completed by ASELSTM** 2022-01-07 11:46 UTC
Labels: internal bug tracker, cube mx, st community

**Comment by ASELSTM** [comment] 2022-01-07 12:15
ST Internal Reference: 120476
